# Generated by Django 3.2.7 on 2023-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230920_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.SmallIntegerField(default=1),
        ),
    ]
