# Generated by Django 3.2.7 on 2023-09-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='new channel', max_length=150),
        ),
    ]
